md "Todos os Clubes"
cd "Todos os Clubes"

md "Serie A"
md "Serie B"

cd "Serie A"
md "Atletico-MG"
md "Palmeiras"
md "Fortaleza"
md "Bragantino"
md "Flamengo"
md "Athletico-PR"
md "Atletico-GO"
md "Ceara"
md "Internacional"
md "Santos"
md "Corinthians"
md "Juventude"
md "Bahia"
md "Sao Paulo"
md "Fluminense"
md "Cuiaba"
md "Sport"
md "America-MG"
md "Gremio"
md "Chapecoense"