md "Todos os paises"
cd "Todos os paises"

md "Argentina" "Bolivia" "Brasil" "Chile" "Colombia" "Equador" "Guiana" "Guiana Francesa" "Paraguai" "Peru" "Suriname" "Uruguai" "Venezuela"

cd "Brasil"

md "Acre
md "Alagoas"
md "Amapa"
md "Amazonas"
md "Bahia"
md "Ceara"
md "Espirito Santo"
md "Goias"
md "Maranhao"
md "Mato Grosso"
md "Mato Grosso do Sul"
md "Minas Gerais"
md "Para"
md "Paraiba"
md "Parana"
md "Pernambuco"
md "Piaui"
md "Rio de Janeiro"
md "Rio Grande do Norte"
md "Rio Grande do Sul"
md "Rondonia"
md "Roraima"
md "Santa Catarina"
md "Sao Paulo"
md "Sergipe"
md "Tocantins"
md "Distrito Federal"
